language: python
sudo: false
python:
  - 2.6
  - 2.7
  - '2.7.8'
  - 3.3
  - 3.4
  - 3.5
  - 3.6

matrix:
  fast_finish: true

cache: pip
notifications:
  email:
    - thierryschellenbach@gmail.com
    - tbarbugli@gmail.com

install:
  - pip install -r dev_requirements.txt
script:
  - py.test stream/tests.py -lv --cov stream --cov-report term-missing
after_script:
  # ensure we validate against pep standards
  - "pep8 --exclude=migrations --ignore=E501,E225,W293 stream"
after_success:
   - coveralls
